#!/bin/sh

if [ "$1" != "upgrade" ]; then
    exit 0
fi

NGINX_CONF='/usr/local/vesta/nginx/conf/nginx.conf'

if [ ! -f "$NGINX_CONF" ]; then
    exit 0
fi

if grep -qE '^[[:space:]]*ssl[[:space:]]+on[[:space:]]*;' "$NGINX_CONF"; then
    echo "=== Patching deprecated nginx SSL configuration ==="

    sed -i -E \
        '/^[[:space:]]*listen[[:space:]].*ssl[[:space:]]*;/! s/^([[:space:]]*listen[[:space:]][^;]*);/\1 ssl;/' \
        "$NGINX_CONF"

    sed -i -E \
        '/^[[:space:]]*ssl[[:space:]]+on[[:space:]]*;/d' \
        "$NGINX_CONF"

elif grep -qE '^[[:space:]]*listen[[:space:]].*[[:space:]]ssl[[:space:]]*;' "$NGINX_CONF"; then
    NGINX_ALREADY_PATCHED=1
else
    echo "=== WARNING: Unable to detect nginx SSL configuration ==="
fi

exit 0
