[Definition]

failregex = ^\s*auth\([^,]*,<ADDR>,sasl:[^)]+\)(?:<[^>]+>)?:\s+Info:\s+passwd-file:\s+missing passwd file:\s+/etc/exim4/domains/[^/\s]*/passwd\s*$

ignoreregex =

datepattern = {^LN-BEG}
